

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./styles:/usr/share/nginx/html/styles
      - ./scripts:/usr/share/nginx/html/scripts
